const{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({headless:true});const c=await b.newContext({viewport:{width:1440,height:1000}});const p=await c.newPage();let out=[];const branch='https://sinisterdiesel.com/?BranchKey=b5afdddae9601468481279b3c52b007d';await p.goto(branch);await p.waitForTimeout(700);
async function test(name,fn){try{await fn();out.push({name,pass:true})}catch(e){out.push({name,pass:false,error:e.message})}}
await test('Search dialog opens, focuses, escapes and restores',async()=>{let op=p.locator('[data-v2-search-open]').first();await op.focus();await op.click();await p.waitForTimeout(200);if(!(await p.locator('[data-v2-search]').evaluate(e=>e.classList.contains('is-open'))))throw Error('not open');if(!(await p.locator('[data-v2-search-input]').evaluate(e=>document.activeElement===e)))throw Error('input not focused');await p.keyboard.press('Escape');if(await p.locator('[data-v2-search]').evaluate(e=>e.classList.contains('is-open')))throw Error('did not close');if(!(await op.evaluate(e=>document.activeElement===e)))throw Error('focus not restored')});
await test('Garage opens and dependent fields work',async()=>{await p.locator('[data-v2-garage-toggle]').first().click();await p.waitForTimeout(150);if(!(await p.locator('[data-v2-garage]').evaluate(e=>e.classList.contains('is-open'))))throw Error('not open');const make=p.locator('[data-v2-garage-field="make"]');await make.selectOption({index:1});if(await p.locator('[data-v2-garage-field="engine"]').isDisabled())throw Error('engine still disabled');await p.keyboard.press('Escape')});
await test('Cart drawer opens and closes',async()=>{await p.locator('[data-v2-cart-open]').first().click();await p.waitForTimeout(150);if(!(await p.locator('[data-v2-cart]').evaluate(e=>e.classList.contains('is-open'))))throw Error('not open');await p.keyboard.press('Escape');if(await p.locator('[data-v2-cart]').evaluate(e=>e.classList.contains('is-open')))throw Error('did not close')});
await test('Desktop mega menu opens and closes',async()=>{const t=p.locator('[data-v2-menu-trigger="1"]').first();await t.hover();await p.waitForTimeout(250);if((await t.getAttribute('aria-expanded'))!=='true')throw Error('aria not expanded');await p.keyboard.press('Escape');if((await t.getAttribute('aria-expanded'))!=='false')throw Error('aria not collapsed')});
await p.goto('https://sinisterdiesel.com/search.html?Search=air+intake');await p.waitForTimeout(600);
await test('Search renders real result count',async()=>{let txt=await p.locator('body').innerText();if(!/results?|products?/i.test(txt))throw Error('no result text')});
await p.goto('https://sinisterdiesel.com/air-intakes-parts-for-powerstroke.html');await p.waitForTimeout(600);
await test('Category controls and products render',async()=>{if(await p.locator('.sd2-v2-product-card,.product-item').count()<1)throw Error('no products');if(await p.locator('select').count()<1)throw Error('no sorting/filter controls')});
await p.goto('https://sinisterdiesel.com/sinister-diesel-cold-air-intake-for-2001-2004-chevygmc-duramax-66l-lb7.html');await p.waitForTimeout(800);
await test('PDP quantity stepper updates',async()=>{const q=p.locator('[data-v2-qty-input]');let a=Number(await q.inputValue());await p.locator('[data-v2-qty-plus]').click();let z=Number(await q.inputValue());if(z!==a+1)throw Error(`quantity ${a}->${z}`)});
await test('PDP sticky product matches hero',async()=>{let hero=(await p.locator('.sd2-v2-product-hero h1').innerText()).trim().toLowerCase();let sticky=(await p.locator('[data-v2-sticky-buy] strong').innerText()).trim().toLowerCase();if(hero!==sticky)throw Error(`mismatch: ${sticky}`)});
// Mobile shell
const mc=await b.newContext({viewport:{width:390,height:844},isMobile:true});const m=await mc.newPage();await m.goto(branch);await m.waitForTimeout(600);
await test('Mobile navigation opens, accordion works, escapes',async()=>{await m.locator('[data-v2-drawer-open]').click();await m.waitForTimeout(150);const d=m.locator('[data-v2-drawer]');if((await d.getAttribute('aria-hidden'))!=='false')throw Error('drawer hidden');const acc=d.locator('[data-v2-acc]').first();await acc.click();if((await acc.getAttribute('aria-expanded'))!=='true')throw Error('accordion failed');await m.keyboard.press('Escape');if((await d.getAttribute('aria-hidden'))!=='true')throw Error('drawer failed close')});
console.log(JSON.stringify(out,null,2));require('fs').writeFileSync('functional-report.json',JSON.stringify(out,null,2));await b.close();process.exit(out.some(x=>!x.pass)?1:0)})();
